resource "aws_key_pair" "jenkins_demo_ssh_key" {
  key_name = "proxy-deployer-key"
  public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQtYeToDv1NpaBwGhkWvL9xB0rBNPZ58j3bs5BJ2df3ZMLcK+zbsIFJHX/QQBsdTnJiLqhPUttANatZheTOW5KsLVb9mxs6jR+Qlu/VPSX6lLP2XAKK4kHRnsRhryXIVhVCup/dcgHxaWsfhxHHSxxz+2IJ/zMHBcKwP2oQLAPq0m6JWkufVT4ZIvKI/9o/eNZ8nzul2tbPs7ZDWe/slaHopQ/nqcHjfOSftgr6qhMoTEuhgwq2Zs145vQGLLkeozKqhk6FPK92BID1DD4ZO2wI6rtl8byWDOBMVVhZPUR9A7mi0Wi8hAoar3TvCALBKEsUG9QHLQbAmHNlg/fZJAr Jenkins pipeline key"
}